/**
 * Top US companies (America) and Top IT companies (India) for coding question assignments.
 * Used by seed-coding-questions to assign "asked at these companies" to each question.
 */

export const US_COMPANIES = [
  "Apple", "Microsoft", "Google", "Amazon", "Meta", "Berkshire Hathaway", "JPMorgan Chase",
  "Visa", "Walmart", "Johnson & Johnson", "Procter & Gamble", "UnitedHealth", "Exxon Mobil",
  "Chevron", "Mastercard", "Alphabet", "Home Depot", "Merck", "AbbVie", "Costco",
  "PepsiCo", "Coca-Cola", "NVIDIA", "Netflix", "Adobe", "Salesforce", "Oracle", "Cisco",
  "Intel", "IBM", "Qualcomm", "Texas Instruments", "AMD", "HP", "Dell", "VMware",
  "ServiceNow", "Workday", "Intuit", "PayPal", "Stripe", "Square", "Spotify", "Uber",
  "Lyft", "Airbnb", "Twitter", "Snap", "Zoom", "Slack", "Atlassian", "Snowflake",
  "Datadog", "CrowdStrike", "Zscaler", "Palo Alto Networks", "Fortinet", "Okta",
  "Twilio", "Shopify", "Etsy", "DoorDash", "Grubhub", "Instacart", "Robinhood",
  "Coinbase", "Kraken", "Goldman Sachs", "Morgan Stanley", "Bank of America",
  "Wells Fargo", "Citigroup", "BlackRock", "Charles Schwab", "American Express",
  "Capital One", "Discover", "Chase", "Cigna", "Anthem", "Kaiser Permanente",
  "McKesson", "AmerisourceBergen", "Cardinal Health", "Boeing", "Lockheed Martin",
  "Northrop Grumman", "Raytheon", "General Dynamics", "Honeywell", "3M",
  "General Electric", "United Parcel Service", "FedEx", "Delta Air Lines",
  "American Airlines", "Southwest Airlines", "Comcast", "AT&T", "Verizon",
  "T-Mobile", "Charter Communications", "Disney", "Warner Bros", "NBCUniversal",
  "Target", "Lowe's", "Best Buy", "Starbucks", "McDonald's", "Yum Brands",
  "Chipotle", "Domino's", "Nike", "Adidas", "Under Armour", "Tesla", "Ford",
  "General Motors", "Rivian", "Lucid", "Waymo", "Cruise", "Zoox",
  "Palantir", "Bloomberg", "S&P Global", "Moody's", "Fiserv", "Fidelity",
  "State Street", "Aon", "Marsh McLennan", "Accenture", "Deloitte", "PwC", "EY",
  "KPMG", "McKinsey", "BCG", "Bain", "Capgemini", "Cognizant", "Infosys",
  "Wipro", "HCL Technologies", "Tech Mahindra", "Tata Consultancy Services",
  "EPAM", "Luxoft", "Globant", "Thoughtworks", "Slalom", "Booz Allen",
  "Leidos", "CACI", "SAIC", "General Atomics", "SpaceX", "Blue Origin",
  "Rocket Lab", "Relativity Space", "Lucid Motors",
  "Dropbox", "Box", "DocuSign", "Twilio", "SendGrid", "Mailchimp", "HubSpot",
  "Zendesk", "Freshworks", "Sprout Social", "Hootsuite", "Canva", "Figma",
  "InVision", "Miro", "Notion", "Airtable", "Asana", "Monday.com", "Trello",
  "Smartsheet", "ServiceTitan", "Procore", "Autodesk", "Ansys", "Cadence",
  "Synopsys", "Lam Research", "Applied Materials", "KLA", "ASML",
  "Micron", "Western Digital", "Seagate", "Broadcom", "Marvell", "Analog Devices",
  "Microchip", "ON Semiconductor", "NXP", "STMicroelectronics", "Arm",
  "Splunk", "Elastic", "MongoDB", "Redis", "Databricks", "Confluent",
  "HashiCorp", "GitLab", "GitHub", "Bitbucket", "JetBrains",
];

export const INDIA_IT_COMPANIES = [
  "Tata Consultancy Services", "TCS", "Infosys", "Wipro", "HCL Technologies",
  "Tech Mahindra", "Capgemini India", "Cognizant India", "Accenture India",
  "IBM India", "Microsoft India", "Google India", "Amazon India", "Oracle India",
  "SAP India", "Salesforce India", "Adobe India", "VMware India", "Cisco India",
  "Intel India", "Qualcomm India", "NVIDIA India", "AMD India", "Dell India",
  "HP India", "Persistent Systems", "L&T Infotech", "LTI Mindtree", "Mphasis",
  "Hexaware", "Zensar", "Cyient", "L&T Technology Services", "KPIT Technologies",
  "Coforge", "Birlasoft", "Sonata Software", "Redington", "Happiest Minds",
  "Newgen Software", "NIIT Technologies", "Mindtree", "Larsen & Toubro Infotech",
  "Genpact", "EXL Service", "WNS", "Conduent", "DXC Technology India",
  "NTT Data India", "Deloitte India", "EY India", "KPMG India", "PwC India",
  "Zoho", "Freshworks", "Chargebee", "Postman", "Razorpay", "PhonePe",
  "Paytm", "Flipkart", "Ola", "Swiggy", "Zomato", "Byju's", "Unacademy",
  "ShareChat", "Meesho", "Cred", "Groww", "PolicyBazaar", "Nykaa",
  "MakeMyTrip", "OYO", "Dream11", "InMobi", "Mu Sigma", "Fractal Analytics",
  "Tiger Analytics", "LatentView", "BRIDGEi2i", "Absolutdata", "Capillary",
  "CleverTap", "MoEngage", "Uniphore", "Exotel", "Gupshup", "Yellow Messenger",
  "Haptik", "Wingify", "BrowserStack", "LambdaTest", "Thoughtworks India",
  "EPAM India", "Publicis Sapient", "Virtusa", "Symphony Teleca", "UST Global",
  "Cognizant", "Deloitte USI", "Tata Elxsi", "KPIT", "Cyient", "LTTS",
];
